/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coins.glb --transform 
Files: coins.glb [6.39MB] > /home/liam/Desktop/Projects/Portfolio/PortfolioAssets/coins-transformed.glb [825.6KB] (87%)
Author: Kirill1991 (https://sketchfab.com/Kirill1991)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coins-a43b47f4eed140a9bd0f5d05849140df
Title: Coins
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Coins(props) {
  const { nodes, materials } = useGLTF('/3D/coins-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.coinsCoin1SG} rotation={[-Math.PI / 2, -Math.PI / 2, Math.PI/3]} />
    </group>
  )
}

useGLTF.preload('/coins-transformed.glb')
