/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 curtains.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Curtains(props) {
  const { nodes, materials } = useGLTF('/3D/curtains-transformed.glb')
  return (
    <group {...props} dispose={null}>
       <mesh geometry={nodes.Studio_Setup_Curtain_3001.geometry} material={materials.Studio_Fabric_3} position={[-0.852, 0, -4.834]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.652} />
    </group>
  )
}

useGLTF.preload('/3D/curtains-transformed.glb')
