/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/3D/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Laptop_TouchPad} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.LaptopLight} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.LaptopButtons} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.LaptopBody} />
      </group>
      <mesh geometry={nodes.LaptopMontor.geometry} material={materials.LaptopScreen} position={[-0.258, 0.016, 0]} rotation={[0, 0, 2.286]} />
    </group>
  )
}

useGLTF.preload('/3D/laptop-transformed.glb')
