/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lego_bricks.glb --transform 
Files: lego_bricks.glb [34.77MB] > /home/liam/Desktop/Projects/Portfolio/PortfolioAssets/lego_bricks-transformed.glb [2.09MB] (94%)
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lego-bricks-55446142c5d54d0e8350246d3c3e3423
Title: Lego Bricks
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lego(props) {
  const { nodes, materials } = useGLTF('3D/lego_bricks-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lego_with_Bump_Green_0.geometry} material={materials.PaletteMaterial002} position={[2.981, 0, 256.267]} rotation={[-Math.PI / 2.2, 0, -2.818]} scale={100} />
    </group>
  )
}

useGLTF.preload('/lego_bricks-transformed.glb')
