/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rectangleLight.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RectangleLight(props) {
  const { nodes, materials } = useGLTF('/3D/rectangleLight.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SoftLight_01.geometry} material={materials['Material.001']} position={[-1.783, 1.961, -0.925]} rotation={[Math.PI / 2, 0, -0.007]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_01001.geometry} material={materials['Material.002']} position={[-1.784, 1.972, -1.046]} rotation={[Math.PI / 2, 0, -0.007]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_01002.geometry} material={materials['Material.002']} position={[-1.788, 1.972, -1.548]} rotation={[Math.PI / 2, 0, -0.007]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_01003.geometry} material={materials['Material.002']} position={[-1.787, 0.606, -1.469]} rotation={[Math.PI / 2, 0, -0.007]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_01004.geometry} material={materials['Material.002']} position={[-1.787, 1.025, -1.461]} rotation={[Math.PI / 2, 0, -0.007]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/3D/rectangleLight.glb')
