/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 roofLight.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RoofLight(props) {
  const { nodes, materials } = useGLTF('/3D/roofLight-transformed.glb')
  return (
    <group rotation={[Math.PI/2, 0, 0]} {...props} dispose={null}>
      <mesh geometry={nodes.SoftLight_01.geometry} material={materials['Material.001']} position={[-1.783, 1.961, -0.925]} rotation={[Math.PI / 2, Math.PI/2, 0]} scale={[0.01,0.001,0.02]} />
      <mesh geometry={nodes.SoftLight_01001.geometry} material={materials['Material.002']} position={[-1.784, 1.972, -1.046]} rotation={[Math.PI / 2, Math.PI/2, 0]} scale={[0.01,0.001,0.02]} />
    </group>
  )
}

useGLTF.preload('/3D/roofLight-transformed.glb')
