/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 softLightHanging.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function SoftLightHanging(props) {
  const { nodes, materials } = useGLTF('/3D/softLightHanging-transformed.glb');
  return (
    <group {...props} dispose={null}>
       <mesh geometry={nodes.SoftLight_08.geometry} material={materials.wire_115115115} position={[0.313, 3.43, -0.025]} rotation={[Math.PI / 2, 0, 1.562]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_08001.geometry} material={materials['Material.002']} position={[0.311, 3.735, -0.238]} rotation={[Math.PI / 2, 0, 1.562]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_08004.geometry} material={materials['Material.010']} position={[0.313, 3.418, 0.02]} rotation={[Math.PI / 2, 0, 1.562]} scale={0.001} />
    </group>
  );
}

useGLTF.preload('/3D/softLightHanging-transformed.glb');
