/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 longLog.glb --transform 
Files: longLog.glb [77.19MB] > /home/liam/Desktop/Projects/Portfolio/portfolio/public/3D/longLog-transformed.glb [1.22MB] (98%)
*/

import React, {useEffect} from 'react'
import { useGLTF } from '@react-three/drei'

export function LongLog(props) {
  const { nodes, materials } = useGLTF('/3D/longLog-transformed.glb')
  useEffect(() => {
    if (materials.Burnt) {
      materials.Burnt.emissiveIntensity = 2
    }
  }, [materials]) 
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Burnt} position={[1.003, 0.908, 0]} />
    </group>
  )
}

useGLTF.preload('/3D/longLog-transformed.glb')
