/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 longLog.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LongLog(props) {
  const { nodes, materials } = useGLTF('/3D/longLog.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Burnt} position={[1.003, 0.908, 0]} rotation={[-Math.PI, 0.011, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/longLog.glb')
