/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shrub.glb 
*/
//created by Natural_Disbuster at https://skfb.ly/o78Yp

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import * as THREE from 'three'

export function Shrub(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3D/shrub-transformed.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action)=>{
        action.play()
      })
    }
  }, [actions]);

  useEffect(() => {
    if (materials.gbushy) {
      materials.gbushy.transparent = true; 
      materials.gbushy.opacity = 1;
      materials.gbushy.alphaTest = 0.5;
      materials.gbushy.depthWrite = false; 
      materials.gbushy.depthTest = true; 
      materials.gbushy.side = THREE.DoubleSide; 
    }
  }, [materials]);
  

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="leaves" geometry={nodes.leaves.geometry} material={materials.gbushy} morphTargetDictionary={nodes.leaves.morphTargetDictionary} morphTargetInfluences={nodes.leaves.morphTargetInfluences} />
      </group>
    </group>
  )
}


useGLTF.preload('/3D/shrub-transformed.glb');
