/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocks.glb --transform 
Files: rocks.glb [6MB] > /home/liam/Desktop/Projects/Portfolio/portfolio/public/3D/rocks-transformed.glb [462.54KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocks-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.namaqualand_boulders_01_a_LOD3.geometry} material={materials.namaqualand_boulders_01} position={[0.681, 0, -0.02]} />
    </group>
  )
}

useGLTF.preload('/rocks-transformed.glb')
