/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 softLightStand.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/softLightStand.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SoftLight_03.geometry} material={materials['Material.002']} position={[1.173, 2.331, -1.491]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03001.geometry} material={materials['Material.002']} position={[0.944, 2.203, -1.238]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03002.geometry} material={materials['Material.002']} position={[1.246, 2.84, -1.756]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03003.geometry} material={materials['Material.002']} position={[0.965, 0.514, -1.65]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03004.geometry} material={materials['Material.002']} position={[1.246, 2.875, -1.494]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03005.geometry} material={materials['Material.002']} position={[1.246, 2.778, -1.224]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03006.geometry} material={materials['Material.002']} position={[1.239, 0.637, -0.914]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03007.geometry} material={materials['Material.002']} position={[1.247, 2.844, -1.493]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03008.geometry} material={materials['Material.002']} position={[1.246, 2.834, -1.223]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03009.geometry} material={materials['Material.002']} position={[1.246, 2.623, -1.19]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03010.geometry} material={materials['Material.002']} position={[1.246, 2.834, -1.215]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03011.geometry} material={materials['Material.010']} position={[1.246, 2.834, -1.201]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03012.geometry} material={materials.wire_115115115} position={[1.246, 2.834, -1.266]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03013.geometry} material={materials['Material.002']} position={[1.246, 2.834, -1.142]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03014.geometry} material={materials.wire_115115115} position={[1.246, 2.852, -1.182]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03015.geometry} material={materials['Material.002']} position={[1.246, 2.833, -1.087]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03016.geometry} material={materials.wire_115115115} position={[1.246, 2.79, -1.664]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03017.geometry} material={materials['Material.002']} position={[1.247, 2.347, -1.49]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03018.geometry} material={materials['Material.002']} position={[1.248, 1.592, -1.491]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03019.geometry} material={materials.wire_115115115} position={[1.324, 2.139, -1.491]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03020.geometry} material={materials['Material.002']} position={[1.239, 0.514, -1.175]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03021.geometry} material={materials['Material.002']} position={[0.738, 0.637, -1.78]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03022.geometry} material={materials['Material.002']} position={[1.513, 0.514, -1.65]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03023.geometry} material={materials['Material.002']} position={[1.739, 0.637, -1.781]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
      <mesh geometry={nodes.SoftLight_03024.geometry} material={materials['Material.002']} position={[1.249, 2.804, -1.49]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/softLightStand.glb')
