/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spacesuit.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/spacesuit.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.579, 0.48, 0.172]} rotation={[1.925, 0.406, -2.131]}>
        <primitive object={nodes.Spine} />
        <mesh geometry={nodes.SpaceSuit_SuitMat_0003.geometry} material={materials['SuitMat.001']} />
        <mesh geometry={nodes.SpaceSuit_SuitMat_0003_1.geometry} material={materials['HelmetMat.001']} />
      </group>
      <mesh geometry={nodes.Object_7003.geometry} material={materials['BackpackMat.001']} position={[-1.084, -0.032, 0.005]} rotation={[0.386, -0.009, -0.003]} scale={0.006} />
      <mesh geometry={nodes.dead_tree_trunk_02_LOD3.geometry} material={materials.dead_tree_trunk_02} position={[0, 0.079, 0]} rotation={[-2.753, -0.055, 3.008]} />
    </group>
  )
}

useGLTF.preload('/spacesuit.glb')
