/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 curtains.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Curtains(props) {
  const { nodes, materials } = useGLTF('/3D/curtains.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Studio_Setup_Curtain_3001.geometry} material={materials.Studio_Fabric_3} position={[-0.852, 0, -4.834]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_1.geometry} material={materials.Studio_Fabric_3} position={[-3.276, 0, -2.454]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_8.geometry} material={materials.Studio_Fabric_3} position={[-0.845, 0, 4.836]} rotation={[Math.PI / 2, 0, 0]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_2.geometry} material={materials.Studio_Fabric_3} position={[-3.208, 0, 2.448]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_3002.geometry} material={materials.Studio_Fabric_3} position={[4.019, 0, 4.826]} rotation={[Math.PI / 2, 0, 0.005]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_1001.geometry} material={materials.Studio_Fabric_3} position={[6.455, 0, 2.458]} rotation={[Math.PI / 2, 0, -1.566]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_8001.geometry} material={materials.Studio_Fabric_3} position={[4.061, 0, -4.844]} rotation={[Math.PI / 2, 0, -3.137]} scale={0.652} />
      <mesh geometry={nodes.Studio_Setup_Curtain_2001.geometry} material={materials.Studio_Fabric_3} position={[6.412, 0, -2.444]} rotation={[Math.PI / 2, 0, -1.566]} scale={0.652} />
    </group>
  )
}

useGLTF.preload('/3D/curtains.glb')
