/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/3D/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.LaptopBody} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Laptop_TouchPad} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.LaptopLight} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.LaptopButtons} />
      </group>
      <group position={[-0.258, 0.016, 0]} rotation={[0, 0, 2.286]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.LaptopBody} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.LaptopScreen} />
      </group>
      <mesh geometry={nodes.LaptopConnecter.geometry} material={materials.LaptopBody} position={[-0.257, 0.018, -0.169]} rotation={[Math.PI / 2, 0, 0]} scale={[0.004, 0.013, 0.004]} />
      <mesh geometry={nodes.LaptopConnecter001.geometry} material={materials.LaptopBody} position={[-0.257, 0.018, 0.149]} rotation={[Math.PI / 2, 0, 0]} scale={[0.004, 0.013, 0.004]} />
    </group>
  )
}

useGLTF.preload('/3D/laptop.glb')
