/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mobile.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mobile(props) {
  const { nodes, materials } = useGLTF('/3D/mobile.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.phone} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.black_bit} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.screen} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials.lens} />
    </group>
  )
}

useGLTF.preload('/mobile.glb')
