/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pig.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pig(props) {
  const { nodes, materials } = useGLTF('/3D/pig.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Sphere.geometry} material={materials.Sphere_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow geometry={nodes.Sphere001.geometry} material={materials.Sphere_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow geometry={nodes.Sphere002.geometry} material={materials.Sphere_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh receiveShadow castShadow geometry={nodes.Sphere003.geometry} material={materials.Sphere_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow geometry={nodes.Tube.geometry} material={materials.Sphere_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow geometry={nodes.Tube001.geometry} material={materials.Sphere_2} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3D/pig.glb')
