/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scaffold.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scaffold(props) {
  const { nodes, materials } = useGLTF('/3D/scaffold.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ferma.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma001.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma002.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma003.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma004.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma005.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma006.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma007.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma008.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma009.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Ferma010.geometry} material={materials['Material.004']} position={[0.302, 0, 1.992]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/3D/scaffold.glb')
