/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 softLightStand.glb 
*/

import React from 'react'
import { Gltf, useGLTF } from '@react-three/drei'

export function SoftLightStand(props) {
  return (
    <Gltf {...props} src={'/3D/softLightStand.glb'} />
  )
}

useGLTF.preload('/3D/softLightStand.glb')
