/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dandelion.glb 
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function DandelionB(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/3D/dandelion/dandelion.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);
  return (
    <group scale={6} ref={group} {...props} dispose={null}>
      <mesh
        name="dandelion_01_b_LOD3"
        geometry={nodes.dandelion_01_b_LOD3.geometry}
        material={materials.dandelion_01}
        morphTargetDictionary={nodes.dandelion_01_b_LOD3.morphTargetDictionary}
        morphTargetInfluences={nodes.dandelion_01_b_LOD3.morphTargetInfluences}
      />
    </group>
  );
}

export function DandelionA(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/3D/dandelion/dandelion.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);
  return (
    <group scale={6} ref={group} {...props} dispose={null}>
      <mesh
        name="dandelion_01_a_LOD3"
        geometry={nodes.dandelion_01_a_LOD3.geometry}
        material={materials.dandelion_01}
        morphTargetDictionary={nodes.dandelion_01_a_LOD3.morphTargetDictionary}
        morphTargetInfluences={nodes.dandelion_01_a_LOD3.morphTargetInfluences}
      />
    </group>
  );
}
export function DandelionC(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/3D/dandelion/dandelion.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);
  return (
    <group scale={6} ref={group} {...props} dispose={null}>
      <mesh
        name="dandelion_01_e_LOD3"
        geometry={nodes.dandelion_01_e_LOD3.geometry}
        material={materials.dandelion_01}
        morphTargetDictionary={nodes.dandelion_01_e_LOD3.morphTargetDictionary}
        morphTargetInfluences={nodes.dandelion_01_e_LOD3.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload('/3D/dandelion/dandelion.glb');
