/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dandelionB.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dandelionB.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dandelion_01_b_LOD3.geometry} material={materials.dandelion_01} position={[-1, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/dandelionB.glb')
