/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 log.glb --transform 
Files: log.glb [71.38MB] > /home/liam/Desktop/Projects/Portfolio/portfolio/public/3D/log-transformed.glb [1.01MB] (99%)
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'

export function Log(props) {
  const { nodes, materials } = useGLTF('/3D/log-transformed.glb')
 

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Slice_3.geometry} material={materials.Burnt} />
    </group>
  )
}

useGLTF.preload('/3D/log-transformed.glb')