/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pineTree.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pine(props) {
  const { nodes, materials } = useGLTF('/3D/pineTree.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Circle001_Bark_0.geometry} material={materials['Bark.001']} position={[11.388, -2.023, 0.267]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 139.819]} />
        <mesh geometry={nodes.Plane001_Branches_0.geometry} material={materials['Branches.001']} position={[15.051, 1107.115, -4.877]} rotation={[-2.05, -0.367, 2.206]} scale={[390.439, 235.379, 405.095]} />
        <mesh geometry={nodes.Plane002_Branches_0.geometry} material={materials['Branches.001']} position={[20.216, 958.783, -18.825]} rotation={[-1.041, -0.178, -1.901]} scale={[362.483, 218.525, 376.089]} />
        <mesh geometry={nodes.Plane003_Branches_0.geometry} material={materials['Branches.001']} position={[8.831, 1409.647, -3.094]} rotation={[-2.148, 0.276, 1.174]} scale={[368.717, 222.284, 382.558]} />
        <mesh geometry={nodes.Plane004_Branches_0.geometry} material={materials['Branches.001']} position={[4.052, 1063.921, -8.618]} rotation={[-Math.PI / 2, 0.633, 0]} scale={[390.439, 235.379, 405.095]} />
        <mesh geometry={nodes.Plane005_Branches_0.geometry} material={materials['Branches.001']} position={[18.453, 1367.394, -8.366]} rotation={[-1.629, -0.582, 3.107]} scale={[368.717, 222.284, 382.558]} />
        <mesh geometry={nodes.Plane006_Branches_0.geometry} material={materials['Branches.001']} position={[12.036, 1298.852, -20.86]} rotation={[-1.024, 0.266, -1.2]} scale={[347.585, 209.544, 360.632]} />
        <mesh geometry={nodes.Plane007_Branches_0.geometry} material={materials['Branches.001']} position={[7.048, 1619.459, -7.199]} rotation={[-1.652, 0.431, 0.345]} scale={[320.564, 193.255, 332.597]} />
        <mesh geometry={nodes.Plane008_Branches_0.geometry} material={materials['Branches.001']} position={[15.825, 1572.243, -6.949]} rotation={[-1.924, -0.489, 2.507]} scale={[295.075, 177.888, 306.151]} />
        <mesh geometry={nodes.Plane009_Branches_0.geometry} material={materials['Branches.001']} position={[16.445, 1484.64, -18.172]} rotation={[-1.151, -0.029, -1.62]} scale={[257.051, 154.965, 266.7]} />
        <mesh geometry={nodes.Plane010_Branches_0.geometry} material={materials['Branches.001']} position={[6.732, 1833.645, -10.833]} rotation={[-1.47, 0.528, -0.293]} scale={[267.417, 161.214, 277.455]} />
        <mesh geometry={nodes.Plane011_Branches_0.geometry} material={materials['Branches.001']} position={[13.428, 1720.71, -6.533]} rotation={[-1.995, -0.233, 1.99]} scale={[255.923, 154.285, 265.53]} />
        <mesh geometry={nodes.Plane012_Branches_0.geometry} material={materials['Branches.001']} position={[19.159, 1735.079, -14.955]} rotation={[-1.288, -0.206, -2.145]} scale={[262.878, 158.478, 272.746]} />
        <mesh geometry={nodes.Plane013_Branches_0.geometry} material={materials['Branches.001']} position={[9.01, 1917.394, -14.019]} rotation={[-1.387, 0.153, -0.925]} scale={[217.596, 131.179, 225.764]} />
        <mesh geometry={nodes.Plane014_Branches_0.geometry} material={materials['Branches.001']} position={[11.223, 1879.577, -8.025]} rotation={[-1.874, 0.116, 1.435]} scale={[224.451, 135.312, 232.876]} />
        <mesh geometry={nodes.Plane015_Branches_0.geometry} material={materials['Branches.001']} position={[19.086, 1988.972, -10.276]} rotation={[-1.39, -0.565, -2.785]} scale={[217.596, 131.179, 225.764]} />
        <mesh geometry={nodes.Plane016_Branches_0.geometry} material={materials['Branches.001']} position={[13.467, 2195.699, -15.976]} rotation={[-1.014, -0.246, -1.986]} scale={[215.684, 130.027, 223.78]} />
        <mesh geometry={nodes.Plane017_Branches_0.geometry} material={materials['Branches.001']} position={[9.804, 2129.928, -10.81]} rotation={[-1.723, 0.411, 0.482]} scale={[215.684, 130.027, 223.78]} />
        <mesh geometry={nodes.Plane018_Branches_0.geometry} material={materials['Branches.001']} position={[16.048, 2032.282, -5.639]} rotation={[-1.796, -0.266, 2.447]} scale={[198.505, 119.67, 205.957]} />
        <mesh geometry={nodes.Plane019_Branches_0.geometry} material={materials['Branches.001']} position={[10.734, 2339.396, -14.97]} rotation={[-1.229, 0.13, -1.341]} scale={[199.45, 120.24, 206.937]} />
        <mesh geometry={nodes.Plane020_Branches_0.geometry} material={materials['Branches.001']} position={[10.564, 2421.14, -9.116]} rotation={[-2.124, 0.325, 1.111]} scale={[199.45, 120.24, 206.937]} />
        <mesh geometry={nodes.Plane021_Branches_0.geometry} material={materials['Branches.001']} position={[18.021, 2255.52, -8.339]} rotation={[-1.596, -0.274, 3.061]} scale={[199.45, 120.24, 206.937]} />
        <mesh geometry={nodes.Plane022_Branches_0.geometry} material={materials['Branches.001']} position={[9.186, 2530.984, -12.374]} rotation={[-1.297, 0.429, -0.686]} scale={[175.771, 105.965, 182.369]} />
        <mesh geometry={nodes.Plane023_Branches_0.geometry} material={materials['Branches.001']} position={[12.284, 2570.634, -8.246]} rotation={[-2.073, -0.039, 1.683]} scale={[175.771, 105.965, 182.369]} />
        <mesh geometry={nodes.Plane024_Branches_0.geometry} material={materials['Branches.001']} position={[17.85, 2462.435, -11.805]} rotation={[-1.335, -0.386, -2.512]} scale={[175.771, 105.965, 182.369]} />
        <mesh geometry={nodes.Plane025_Branches_0.geometry} material={materials['Branches.001']} position={[12.036, 2703.403, -13.675]} rotation={[-1.075, 0.098, -1.484]} scale={[127.438, 76.827, 132.221]} />
        <mesh geometry={nodes.Plane026_Branches_0.geometry} material={materials['Branches.001']} position={[11.33, 2675.803, -10.001]} rotation={[-1.953, 0.336, 0.925]} scale={[127.438, 76.827, 132.221]} />
        <mesh geometry={nodes.Plane027_Branches_0.geometry} material={materials['Branches.001']} position={[15.954, 2596.939, -8.749]} rotation={[-1.718, -0.426, 2.859]} scale={[127.438, 76.827, 132.221]} />
        <mesh geometry={nodes.Plane028_Branches_0.geometry} material={materials['Branches.001']} position={[15.345, 2745.262, -12.448]} rotation={[-1.445, -0.163, -2.741]} scale={[115.553, 69.662, 119.891]} />
        <mesh geometry={nodes.Plane029_Branches_0.geometry} material={materials['Branches.001']} position={[11.965, 2804.852, -12.16]} rotation={[-1.437, 0.271, -0.466]} scale={[115.554, 69.662, 119.891]} />
        <mesh geometry={nodes.Plane030_Branches_0.geometry} material={materials['Branches.001']} position={[12.049, 2812.806, -8.059]} rotation={[-1.81, 0.015, 1.602]} scale={[111.106, 66.981, 115.276]} />
        <mesh geometry={nodes.Plane031_Branches_0.geometry} material={materials['Branches.001']} position={[13.043, 2901.364, -13.307]} rotation={[-0.963, -0.081, -1.737]} scale={[98.776, 59.548, 102.483]} />
        <mesh geometry={nodes.Plane032_Branches_0.geometry} material={materials['Branches.001']} position={[11.598, 2977.515, -10.792]} rotation={[-1.778, 0.354, 0.575]} scale={[98.776, 59.548, 102.483]} />
        <mesh geometry={nodes.Plane033_Branches_0.geometry} material={materials['Branches.001']} position={[16.836, 2903.802, -11.567]} rotation={[-1.797, -0.298, 2.521]} scale={[98.776, 59.548, 102.483]} />
        <mesh geometry={nodes.Plane034_Branches_0.geometry} material={materials['Branches.001']} position={[11.912, 2979.688, -12.053]} rotation={[-1.26, 0.236, -1.024]} scale={[68.036, 41.016, 70.59]} />
        <mesh geometry={nodes.Plane035_Branches_0.geometry} material={materials['Branches.001']} position={[12.445, 3050.127, -10.128]} rotation={[-1.965, 0.107, 1.351]} scale={[68.036, 41.016, 70.59]} />
        <mesh geometry={nodes.Plane036_Branches_0.geometry} material={materials['Branches.001']} position={[13.698, 3000.74, -15.378]} rotation={[-1.508, -0.367, -2.924]} scale={[68.036, 41.016, 70.59]} />
        <mesh geometry={nodes.Plane037_Branches_0.geometry} material={materials['Branches.001']} position={[10.297, 3151.18, -13.364]} rotation={[-1.752, 0.345, 0.414]} scale={[63.923, 38.537, 66.323]} />
        <mesh geometry={nodes.Plane038_Branches_0.geometry} material={materials['Branches.001']} position={[15.17, 3103.51, -14.261]} rotation={[-1.765, -0.361, 2.663]} scale={[68.036, 41.016, 70.59]} />
        <mesh geometry={nodes.Plane039_Branches_0.geometry} material={materials['Branches.001']} position={[13.778, 3072.26, -12.686]} rotation={[-1.199, -0.015, -1.564]} scale={[68.036, 41.016, 70.59]} />
        <mesh geometry={nodes.Plane040_Branches_0.geometry} material={materials['Branches.001']} position={[12.036, 2114.074, -13.675]} rotation={[-1.466, 0.285, -0.639]} scale={[197.619, 119.136, 205.037]} />
        <mesh geometry={nodes.st006_Bark_0.geometry} material={materials['Bark.001']} position={[-32.623, 384.6, -43.214]} rotation={[-1.241, 0.223, 1.253]} scale={[-97.698, -120.761, -431.157]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3D/pineTree.gltf')
