/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shrub.glb 
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function ShrubA(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3D/shrub/shrub.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action)=>{
        action.play()
      })
    }
  }, [actions]);

  useEffect(() => {
    if (materials.shrub_01) {
      materials.shrub_01.transparent = false; // Disable transparency
      materials.shrub_01.opacity = 1; // Full opacity
      materials.shrub_01.alphaTest = 0; // Disable alpha testing (if applicable)
      materials.shrub_01.depthWrite = true; // Enable depth writing for proper rendering
    }
  }, [materials]);

  return (
    <group scale={6}  ref={group} {...props} dispose={null}>
      <mesh
        position={[-0.6,0,0]}
        name="shrub_01_a_LOD3"
        geometry={nodes.shrub_01_a_LOD3.geometry}
        material={materials.shrub_01}
        morphTargetDictionary={nodes.shrub_01_a_LOD3.morphTargetDictionary}
        morphTargetInfluences={nodes.shrub_01_a_LOD3.morphTargetInfluences}
      />
    </group>
  );
}

export function ShrubB(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3D/shrub/shrub.glb');
  useEffect(() => {
    if (materials.shrub_01) {
      materials.shrub_01.transparent = false; // Disable transparency
      materials.shrub_01.opacity = 1; // Full opacity
      materials.shrub_01.alphaTest = 0; // Disable alpha testing (if applicable)
      materials.shrub_01.depthWrite = true; // Enable depth writing for proper rendering
    }
  }, [materials]);
  return (
    <group scale={6} ref={group} {...props} dispose={null}>
    <mesh
      name="shrub_01_a_LOD3"
      geometry={nodes.shrub_01_a_LOD3.geometry}
      material={materials.shrub_01}
      morphTargetDictionary={nodes.shrub_01_a_LOD3.morphTargetDictionary}
      morphTargetInfluences={nodes.shrub_01_a_LOD3.morphTargetInfluences}
    />
  </group>
  );
}

useGLTF.preload('/3D/shrub/shrub.glb');
