/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 longLog.glb --transform 
Files: longLog.glb [77.19MB] > /home/liam/Desktop/Projects/Portfolio/portfolio/public/3D/longLog-transformed.glb [1.22MB] (98%)
*/

import React, {useEffect} from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { TextureLoader } from 'three'

export function LongLog(props) {
  const { nodes, materials } = useGLTF('/3D/longLog-transformed.glb')
  const displacementMap = new TextureLoader().load('3D/textures/burnt_wood_height.png')
  useEffect(() => {
    if (materials.Burnt) {
      materials.Burnt.emissiveIntensity = 4
    }
  }, [materials]) 
  return (
    <group {...props} dispose={null}>
      <mesh rotation={[0, 4* Math.PI /3, 0]} geometry={nodes.Cylinder002.geometry} material={materials.Burnt} position={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3D/longLog-transformed.glb')
