/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pine.glb 
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import * as THREE from 'three';

export function Pine(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/3D/pine.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Circle001" position={[11.388, -2.023, 0.267]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 139.819]}>
            <mesh name="Circle001_Bark_0" geometry={nodes.Circle001_Bark_0.geometry} material={materials.pine_tree_01_bark} />
          </group>
          <group name="Plane001" scale={100}>
            <mesh name="Plane001_Branches_0" geometry={nodes.Plane001_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane001_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane001_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane002" scale={100}>
            <mesh name="Plane002_Branches_0" geometry={nodes.Plane002_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane002_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane002_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane003" scale={100}>
            <mesh name="Plane003_Branches_0" geometry={nodes.Plane003_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane003_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane003_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane004" scale={100}>
            <mesh name="Plane004_Branches_0" geometry={nodes.Plane004_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane004_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane004_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane005" scale={100}>
            <mesh name="Plane005_Branches_0" geometry={nodes.Plane005_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane005_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane005_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane006" scale={100}>
            <mesh name="Plane006_Branches_0" geometry={nodes.Plane006_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane006_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane006_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane007" scale={100}>
            <mesh name="Plane007_Branches_0" geometry={nodes.Plane007_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane007_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane007_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane008" scale={100}>
            <mesh name="Plane008_Branches_0" geometry={nodes.Plane008_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane008_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane008_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane009" scale={100}>
            <mesh name="Plane009_Branches_0" geometry={nodes.Plane009_Branches_0.geometry} material={materials.Branches} morphTargetDictionary={nodes.Plane009_Branches_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane009_Branches_0.morphTargetInfluences} />
          </group>
          <group name="Plane010" position={[6.732, 1833.645, -10.833]} rotation={[-1.47, 0.528, -0.293]} scale={[267.417, 161.214, 277.455]}>
            <mesh name="Plane010_Branches_0" geometry={nodes.Plane010_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane011" position={[13.428, 1720.71, -6.533]} rotation={[-1.995, -0.233, 1.99]} scale={[255.923, 154.285, 265.53]}>
            <mesh name="Plane011_Branches_0" geometry={nodes.Plane011_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane012" position={[19.159, 1735.079, -14.955]} rotation={[-1.288, -0.206, -2.145]} scale={[262.878, 158.478, 272.746]}>
            <mesh name="Plane012_Branches_0" geometry={nodes.Plane012_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane013" position={[9.01, 1917.394, -14.019]} rotation={[-1.387, 0.153, -0.925]} scale={[217.596, 131.179, 225.764]}>
            <mesh name="Plane013_Branches_0" geometry={nodes.Plane013_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane014" position={[11.223, 1879.577, -8.025]} rotation={[-1.874, 0.116, 1.435]} scale={[224.451, 135.312, 232.876]}>
            <mesh name="Plane014_Branches_0" geometry={nodes.Plane014_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane015" position={[19.086, 1988.972, -10.276]} rotation={[-1.39, -0.565, -2.785]} scale={[217.596, 131.179, 225.764]}>
            <mesh name="Plane015_Branches_0" geometry={nodes.Plane015_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane016" position={[13.467, 2195.699, -15.976]} rotation={[-1.014, -0.246, -1.986]} scale={[215.684, 130.027, 223.78]}>
            <mesh name="Plane016_Branches_0" geometry={nodes.Plane016_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane017" position={[9.804, 2129.929, -10.81]} rotation={[-1.723, 0.411, 0.482]} scale={[215.684, 130.027, 223.78]}>
            <mesh name="Plane017_Branches_0" geometry={nodes.Plane017_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane018" position={[16.048, 2032.282, -5.639]} rotation={[-1.796, -0.266, 2.447]} scale={[198.505, 119.67, 205.957]}>
            <mesh name="Plane018_Branches_0" geometry={nodes.Plane018_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane019" position={[10.734, 2339.396, -14.97]} rotation={[-1.229, 0.13, -1.341]} scale={[199.45, 120.24, 206.937]}>
            <mesh name="Plane019_Branches_0" geometry={nodes.Plane019_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane020" position={[10.564, 2421.14, -9.116]} rotation={[-2.124, 0.325, 1.111]} scale={[199.45, 120.24, 206.937]}>
            <mesh name="Plane020_Branches_0" geometry={nodes.Plane020_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane021" position={[18.021, 2255.52, -8.339]} rotation={[-1.596, -0.274, 3.061]} scale={[199.45, 120.24, 206.937]}>
            <mesh name="Plane021_Branches_0" geometry={nodes.Plane021_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane022" position={[9.186, 2530.984, -12.374]} rotation={[-1.297, 0.429, -0.686]} scale={[175.771, 105.965, 182.369]}>
            <mesh name="Plane022_Branches_0" geometry={nodes.Plane022_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane023" position={[12.284, 2570.634, -8.246]} rotation={[-2.073, -0.039, 1.683]} scale={[175.771, 105.965, 182.369]}>
            <mesh name="Plane023_Branches_0" geometry={nodes.Plane023_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane024" position={[17.85, 2462.435, -11.805]} rotation={[-1.335, -0.386, -2.512]} scale={[175.771, 105.965, 182.369]}>
            <mesh name="Plane024_Branches_0" geometry={nodes.Plane024_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane025" position={[12.036, 2703.404, -13.675]} rotation={[-1.075, 0.098, -1.484]} scale={[127.438, 76.827, 132.221]}>
            <mesh name="Plane025_Branches_0" geometry={nodes.Plane025_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane026" position={[11.33, 2675.803, -10.001]} rotation={[-1.953, 0.336, 0.925]} scale={[127.438, 76.827, 132.221]}>
            <mesh name="Plane026_Branches_0" geometry={nodes.Plane026_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane027" position={[15.954, 2596.94, -8.749]} rotation={[-1.718, -0.426, 2.859]} scale={[127.438, 76.827, 132.221]}>
            <mesh name="Plane027_Branches_0" geometry={nodes.Plane027_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane028" position={[15.345, 2745.262, -12.448]} rotation={[-1.445, -0.163, -2.741]} scale={[115.553, 69.662, 119.891]}>
            <mesh name="Plane028_Branches_0" geometry={nodes.Plane028_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane029" position={[11.965, 2804.852, -12.16]} rotation={[-1.437, 0.271, -0.466]} scale={[115.554, 69.662, 119.891]}>
            <mesh name="Plane029_Branches_0" geometry={nodes.Plane029_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane030" position={[12.049, 2812.806, -8.059]} rotation={[-1.81, 0.015, 1.602]} scale={[111.106, 66.981, 115.276]}>
            <mesh name="Plane030_Branches_0" geometry={nodes.Plane030_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane031" position={[13.043, 2901.364, -13.307]} rotation={[-0.963, -0.081, -1.737]} scale={[98.776, 59.548, 102.483]}>
            <mesh name="Plane031_Branches_0" geometry={nodes.Plane031_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane032" position={[11.598, 2977.515, -10.792]} rotation={[-1.778, 0.354, 0.575]} scale={[98.776, 59.548, 102.483]}>
            <mesh name="Plane032_Branches_0" geometry={nodes.Plane032_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane033" position={[16.836, 2903.803, -11.567]} rotation={[-1.797, -0.298, 2.521]} scale={[98.776, 59.548, 102.483]}>
            <mesh name="Plane033_Branches_0" geometry={nodes.Plane033_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane034" position={[11.912, 2979.689, -12.053]} rotation={[-1.26, 0.236, -1.024]} scale={[68.036, 41.016, 70.59]}>
            <mesh name="Plane034_Branches_0" geometry={nodes.Plane034_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane035" position={[12.445, 3050.127, -10.128]} rotation={[-1.965, 0.107, 1.351]} scale={[68.036, 41.016, 70.59]}>
            <mesh name="Plane035_Branches_0" geometry={nodes.Plane035_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane036" position={[13.698, 3000.74, -15.378]} rotation={[-1.508, -0.367, -2.924]} scale={[68.036, 41.016, 70.59]}>
            <mesh name="Plane036_Branches_0" geometry={nodes.Plane036_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane037" position={[10.297, 3151.181, -13.364]} rotation={[-1.752, 0.345, 0.414]} scale={[63.923, 38.537, 66.323]}>
            <mesh name="Plane037_Branches_0" geometry={nodes.Plane037_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane038" position={[15.17, 3103.51, -14.261]} rotation={[-1.765, -0.361, 2.663]} scale={[68.036, 41.016, 70.59]}>
            <mesh name="Plane038_Branches_0" geometry={nodes.Plane038_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane039" position={[13.778, 3072.261, -12.686]} rotation={[-1.199, -0.015, -1.564]} scale={[68.036, 41.016, 70.59]}>
            <mesh name="Plane039_Branches_0" geometry={nodes.Plane039_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="Plane040" position={[12.036, 2114.074, -13.675]} rotation={[-1.466, 0.285, -0.639]} scale={[197.619, 119.136, 205.037]}>
            <mesh name="Plane040_Branches_0" geometry={nodes.Plane040_Branches_0.geometry} material={materials.Branches} />
          </group>
          <group name="st006" position={[-32.623, 384.6, -43.214]} rotation={[-1.241, 0.223, 1.253]} scale={[-97.698, -120.761, -431.157]}>
            <mesh name="st006_Bark_0" geometry={nodes.st006_Bark_0.geometry} material={materials.pine_tree_01_bark} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3D/pine.glb');
