/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocks.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RockA(props) {
  const { nodes, materials } = useGLTF('/3D/rocks.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow  geometry={nodes.namaqualand_boulders_01_a_LOD3.geometry} material={materials.namaqualand_boulders_01} />
    </group>
  )
}

export function RockB(props) {
  const { nodes, materials } = useGLTF('/3D/rocks.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow  geometry={nodes.namaqualand_boulders_01_b_LOD3.geometry} material={materials.namaqualand_boulders_01} />
    </group>
  )
}

useGLTF.preload('/3D/rocks.glb')
